### ISSUE TITLE
Apple Watch

### ISSUE THREAD

**Issue by bassrock** [fastlane/snapshot#121]
Ok, I'll be that guy. With submissions now allowed and the guidelines set. Apple watch screenshot support would be awesome or this awesome toolset!

The guidelines are here: https://developer.apple.com/app-store/watch/

**Comment by bassrock** [comment]
Damn. This may not even be possible for the time being.

https://developer.apple.com/library/ios/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html

UIAutomation is not available for the Watch with the current Xcode release.

**Comment by KrauseFx** [comment]
Oh, but does that mean Apple is working on it?

**Comment by bassrock** [comment]
I would hope so. It seems like the Watch acts as an external display in the simulator, and this is technicality the first "external iOS device" so who knows.. The other solution that could be jerry rigged is something that controls the mouse input but that should only be if  gives us no solution anytime soon.

**Comment by kostiakoval** [comment]
- Can't run snapshot for the iOS app that includes Apple Watch target

Steps: 
- Create new iOS app with Watch OS 2
- run snapshot init
- run snapshot

Get Error: 

"target specifies product type 'com.apple.product-type.watchkit2-extension', but there's no such product type for the 'iphonesimulator' platform"

It should use correct platform form the watch target

**Comment by jcampbell05** [comment]
@KrauseFx Even if this isn't possible it would be awesome if we could use something like this https://dribbble.com/shots/1719044-Apple-Watch-Free-Template-PSD so we can produce mockups of the app for marketing material outside of the app store.

**Comment by artworker** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

artworker@naver.com 님께 보내신 메일 <Re: [snapshot] Apple Watch (#121)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by jcampbell05** [comment]
@bassrock  @KrauseFx  So apple recently changed it so the Apple Watch Simulator is now a seperate simulator. 

- We can in theory find some way of loading it manually.
- People have found ways of using UIKit in the Apple Watch, so in theory it *may* be possible to do this for UIAutomation.
- Failing that we could do some sort of hack where we run a custom scheme for the user or launch the app with a special launch argument which the app picks up and then shows the screen pre-configured. Apple has a system like this for their notification scheme which allows you to specify JSON to populate the notification with.
- After a few seconds we could somehow grab the Window ID of the simulator and take a screenshot.
