### ISSUE TITLE
Blurry none retina images used

### ISSUE THREAD

**Issue by sandman4sure** [fastlane/snapshot#199]
When I use Xcode 7 to compile and test my app on the Simulator, everything is fine, but when I use snapshot the app loads with the none-retina images selected and everything looks blurry.

Any idea what is different between using snapshot to put the app on the simulator and using Xcode7?

(I have xctool installed for compiling, but without it also goes wrong)

This started happening with new Xcode 7 installed, before everything was fine.

Thanks!

**Comment by Shukuyen** [comment]
We have the same issue. On iPhone (where we only have retina images) no images are displayed. On iPad we get the 1x images. This happened after updating to Xcode 7 (using 7.0.1 at the moment) and resetting the simulators.

Did you find a solution, @sandman4sure ?

**Comment by sandman4sure** [comment]
No, sadly not.

**Comment by ZevEisenberg** [comment]
I’m seeing this as well. Not sure about what the simulator is doing, but my screenshots are Retina-size, but each pixel is a cluster of 4 identical pixels. See attached example:

![de-de-ipad-0-landingscreen-portrait](https://cloud.githubusercontent.com/assets/464574/10673057/c1ce00da-78c1-11e5-95f2-21cb7a1a2423.png)

**Comment by jeryRazakarison** [comment]
I had this bug too. I'm using the snapshot js version. (for now, I prefer not to migrate to XCode UI Test, because of #215).

I solved this by deleting all the simulators, and recreating them manually (in xcode 7, it's at Window->Devices).

Hope it helps.
