### ISSUE TITLE
Failed to install using "sudo gem install snapshot"

### ISSUE THREAD

**Issue by plam4u** [fastlane/snapshot#203]
Plamens-Mac-Pro:~ plam$ sudo gem install snapshot
Password:
Fetching: addressable-2.3.8.gem (100%)
Successfully installed addressable-2.3.8
Fetching: fastimage-1.6.8.gem (100%)
Successfully installed fastimage-1.6.8
Fetching: multi_json-1.11.2.gem (100%)
Successfully installed multi_json-1.11.2
Fetching: highline-1.7.7.gem (100%)
Successfully installed highline-1.7.7
Fetching: commander-4.3.5.gem (100%)
Successfully installed commander-4.3.5
Fetching: babosa-1.0.2.gem (100%)
Successfully installed babosa-1.0.2
Fetching: excon-0.45.4.gem (100%)
Successfully installed excon-0.45.4
Fetching: rubyzip-1.1.7.gem (100%)
Successfully installed rubyzip-1.1.7
Fetching: plist-3.1.0.gem (100%)
Successfully installed plist-3.1.0
Fetching: security-0.1.3.gem (100%)
Successfully installed security-0.1.3
Fetching: credentials_manager-0.8.2.gem (100%)
Successfully installed credentials_manager-0.8.2
Fetching: phantomjs-1.9.8.0.gem (100%)
Successfully installed phantomjs-1.9.8.0
Fetching: mime-types-2.6.2.gem (100%)
Successfully installed mime-types-2.6.2
Fetching: rack-1.6.4.gem (100%)
Successfully installed rack-1.6.4
Fetching: rack-test-0.6.3.gem (100%)
Successfully installed rack-test-0.6.3
Fetching: xpath-2.0.0.gem (100%)
Successfully installed xpath-2.0.0
Fetching: capybara-2.4.4.gem (100%)
Successfully installed capybara-2.4.4
Fetching: websocket-extensions-0.1.2.gem (100%)
Successfully installed websocket-extensions-0.1.2
Fetching: websocket-driver-0.6.2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing snapshot:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
creating Makefile

make "DESTDIR="
make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin14/ruby/config.h', needed by `websocket_mask.o'.  Stop.

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/websocket-driver-0.6.2 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/websocket-driver-0.6.2/ext/websocket-driver/gem_make.out

**Comment by ThomasCassany** [comment]
Same issue...

**Comment by KrauseFx** [comment]
Did you make sure to run `sudo xcode-select --install`?

**Comment by joepasq** [comment]
@plam4u I am also seeing this. Running OS X El Capitan, Ruby 2.2.3, and freshly installing `gem install snapshot`. `--verbose` outputs:

```
Building native extensions.  This could take a while...
/usr/local/var/rbenv/versions/2.2.3/bin/ruby -r ./siteconf20151010-44044-f8mjby.rb extconf.rb
creating Makefile
make "DESTDIR=" clean
make "DESTDIR="
compiling websocket_mask.c
linking shared-object websocket_mask.bundle
ld: library not found for -lgmp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [websocket_mask.bundle] Error 1
ERROR:  Error installing snapshot:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
make failed, exit code 2
```

**Comment by joepasq** [comment]
@KrauseFx is this a dependency on `libwebsockets`? I've tried installing libwebsocket through brew and gems, but haven't had any luck.
