### ISSUE TITLE
[UI Testing] Looping waiting for menu bar to clear

### ISSUE THREAD

**Issue by davidrothera** [fastlane/snapshot#213]
When you run the UITesting branch on a simulator that has had it's status bar changed with SimulatorStatusMagic there is a loop.

It is looping waiting for the menu bar to clear as we are waiting for there to be 4 (or less) items in the menu bar, in a fresh simulator there are 4 items:
* Carrier
* WiFi
* Clock
* Battery

When you have run SimulatorStatusMagic though there are 6:
* Carrier name (blank string, I assume)
* Signal Strength
* WiFi
* Clock
* Battery percentage
* Battery

Ideally the code should detect if the simulator has been 'magic'ed and change accordingly :+1:

**Comment by KrauseFx** [comment]
Nice catch, thanks! :+1:

**Comment by ericertl** [comment]
@davidrothera  I changed waitForLoadingIndicatorToDisappear to look for the label "Network connection in progress" instead of hardcoding the number of elements on the statusbar as on iPad there were also more elements.
Hope this helps

```
func waitForLoadingIndicatorToDisappear()
    {
        let query = XCUIApplication().statusBars.childrenMatchingType(.Other).elementBoundByIndex(1).childrenMatchingType(.Other)
        let predicate = NSPredicate(format: "label == 'Network connection in progress'")
        let networkActivity = query.matchingPredicate(predicate)
        
        while (networkActivity.count > 0) {
            sleep(1)
            print("Number of ActivityIndicator Elements in Status Bar: \(networkActivity.count)... waiting for activity indicator to disappear")
        }
    }
```

**Comment by KrauseFx** [comment]
@ericertl I assume this is only working for English apps then, right?

**Comment by ericertl** [comment]
@KrauseFx sadly yes. I'm using @zineer code from #248 with the hardcoded values (4 for iphone, 5 for ipad)

I'm really disappointed that ```let query = XCUIApplication().statusBars.childrenMatchingType(.Other).elementBoundByIndex(1).childrenMatchingType(.ActivityIndicator) ``` doesn't return the loading indicators as it should and that the text for the loading indicator is localized
