### ISSUE TITLE
reset_simulators might fail to remove some simulators

### ISSUE THREAD

**Issue by odrobnik** [fastlane/snapshot#218]
I've had the situation that somehow the permissions of a subfolder of the simulator folder got messed up. A normal `rm -rf UUID` would not work then and you would get a message like I am [showing in this blog post](https://www.cocoanetics.com/2015/10/fixing-the-simulators/)

Running `sudo snapshot reset_simulators` was not able to remove the two offending directories.

Im my case the workaround was to cd into ` ~/Library/Developer/CoreSimulator/Devices` and `sudo rm -rf UUID` to remove them.

I would expect:

1) The message about not being able to remove the folder should be changed to mention the workaround as explained... currently it talks about "... File > Get Info" which is not very helpful. Neither is the Cocoa error message quoted.

2) When run with sudo I would expect the tool to have sufficient permissions to also remove a folder if the contents somehow prevent a plain `rm -rf`

**Comment by KrauseFx** [comment]
Sorry for the delayed reply - somehow lost this tab. Interesting, I haven't seen this issue before. 

This is definitely something where I'd prefer showing a better error message with proper instructions right in `snapshot`.

Thanks for the blog post and the nice words :+1:

**Comment by KrauseFx** [comment]
You should try some of the other `fastlane` tools too, like [gym](https://github.com/fastlane/gym). I wouldn't start setting up `snapshot` for screenshots right now, as I'm currently working on a rewrite using UI Tests instead of UI Automation.
