### ISSUE TITLE
Support for Objective-C tests

### ISSUE THREAD

**Issue by ericertl** [fastlane/snapshot#228]
xcodebuild: error: Scheme fma is not currently configured for the test action.
[14:53:07]: Exit status: 66
[14:53:07]: Cought error... 66
[14:53:07]: Too many errors... no more retries...
/Library/Ruby/Gems/2.0.0/gems/snapshot-1.0.1/lib/snapshot/runner.rb:30:in `work': Too many errors... no more retries...; Too many errors... no more retries...; Too many errors... no more retries... (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.0.1/bin/snapshot:37:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.0.1/bin/snapshot:68:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.0.1/bin/snapshot:74:in `<top (required)>'
	from /usr/bin/snapshot:23:in `load'
	from /usr/bin/snapshot:23:in `<main>'

**Comment by ericertl** [comment]
Nevermind. I saw the .js files are deprecated, and I have to create a test project. 
Figuring out how to make the swift file with objC

**Comment by ericertl** [comment]
So, the only way I could make this work was surrounding SnapshotHelper.swift code inside a class

```code
@objc class SnapshotHelper : NSObject {

    var deviceLanguage = ""

    func setLanguage(app: XCUIApplication)
    {.....
}
```

and in my UITests.m file import the swift header

```code
#import "UITests-Swift.h"
```

and to call the functions I had to create an instance of SnapshotHelper like this

```code
SnapshotHelper *snapshotHelper = [[SnapshotHelper alloc] init];
[snapshotHelper setLanguage:app];
[snapshotHelper snapshot:@"01LoginScreen" waitForLoadingIndicator:YES];
```

If anyone finds a better way to do this, please let me know

**Comment by KrauseFx** [comment]
@ericertl Interesting. I'd love to support Objective-C tests as well :+1:

**Comment by ConfusedVorlon** [comment]
I sent a pull request to support this

**Comment by KrauseFx** [comment]
Thanks @ConfusedVorlon :+1:

**Comment by ericertl** [comment]
@ConfusedVorlon Nice work. @KrauseFx needs to modify SnapshotHelper.swift to be contained in a class with @objc attribute. Otherwise Obj C cannot interact with the swift functions
