### ISSUE TITLE
`snapshot reset_simulators` did not create a simulator for the AppleTV

### ISSUE THREAD

**Issue by zorn** [fastlane/snapshot#243]
Using: OS X 10.11.1, Xcode 7.1, snapshot 1.0.3

When I ran `snapshot reset_simulators` it did not create a simulator for the AppleTV. I was able to manually create one but it curiously showed up as using 9.0 when all the other simulators under Xcode 7.1 were listed as 9.1.

**Comment by ChaosCoder** [comment]
Well, that's because tvOS currently exists only in version 9.0. Other than that: Agree, it didn't recreate AppleTV simulators.

**Comment by kcharwood** [comment]
Seeing the same issue. tvOS Simulator was deleted, and not readded.

**Comment by marksands** [comment]
Same with the Watch for me.
