### ISSUE TITLE
snapshot() hangs when used on iPad Air 2 simulator

### ISSUE THREAD

**Issue by armadsen** [fastlane/snapshot#263]
More specifically, `waitForLoadingIndicatorToDisappear()` seems to be hanging because `query.count > 4) is never false (`query.count` is 5), even though the app has seemingly finished loading. My app hides the status bar on iPhone, so it may affect iPhone too?

The easy workaround is to pass false for `waitForLoadingIndicator:`, of course.

**Comment by ericertl** [comment]
Same issue as #248

**Comment by KrauseFx** [comment]
Please disable waiting for loading indicator for now
