### ISSUE TITLE
Request: when test fails, log device and language again

### ISSUE THREAD

**Issue by emarley** [fastlane/snapshot#282]
At the beginning of a 'test', it neatly prints out what device and language are being used. Then the build proceeds for hundreds of lines of output (scrolling that neat summary way, way off screen). Then, if something horrible happens, there's a test failure, usually unfulfilled expectations. Then snapshot prints this line: 

`Tests failed - check out the log above`

It would be delightful if that were followed by a line like:

`iPad Retina - de`

Or perhaps it could be included in the log, such as: 

`Tests failed (iPad Retina:de) - check out the log above`

**Comment by KrauseFx** [comment]
Thanks for the feedback. Check out the latest version which adds a nice summary table in the end.
