### ISSUE TITLE
Add back SNAPSHOT Preprocessor Macro

### ISSUE THREAD

**Issue by jeffd** [fastlane/snapshot#287]
From a conversation with Felix, he told me to try adding back the flags with the xcrun command. Adding the following code seems to do the trick:

```GCC_PREPROCESSOR_DEFINITIONS='$(inherited) SNAPSHOT=1' OTHER_SWIFT_FLAGS='$(inherited) -DSNAPSHOT'```

Full Command:
```xcrun xcodebuild -showBuildSettings -workspace './MyCoolApp.xcworkspace' -scheme 'MyCoolApp' GCC_PREPROCESSOR_DEFINITIONS='$(inherited) SNAPSHOT=1' OTHER_SWIFT_FLAGS='$(inherited) -DSNAPSHOT'```

**Comment by ConfusedVorlon** [comment]
where are you doing this?

I have experimented with this in test_command_generator.rb, but I get 

	Unknown build action 'GCC_PREPROCESSOR_DEFINITIONS'.

or if I make it -GCC_PREPROCESSOR_DEFINITIONS

	xcodebuild: error: invalid option '-GCC_PREPROCESSOR_DEFINITIONS'

**Comment by jeffd** [comment]
This was just from the command line, changing the one command from the output, I have not modified my snapshot to add those arguments in, I'm not sure where it gets run from poking around the code a little.

**Comment by ConfusedVorlon** [comment]
I ended up getting the same thing through fastlane and environment variables

https://github.com/ConfusedVorlon/snapshot#passing-a-preprocessor-macro

I do think snapshot should just set the variable by default though. I can't see any downside to having it set for all projects.

**Comment by markusloffler** [comment]
Anybody knows if there is any chance to get this officially back into snapshot? That would be really great.

**Comment by ConfusedVorlon** [comment]
yup - there is a pull request in progress:

https://github.com/fastlane/snapshot/pull/310

**Comment by markusloffler** [comment]
Thanks for the link to the pull request. However, this one uses launch arguments, I'd need a solution with preprocessor macros, for two reasons.
- I want to do screenshots of today exentsions, they don't take launch arguments as far as I know
- I prefer not to have screenshot specific code in my app store release

**Comment by ConfusedVorlon** [comment]
my mistake - I was confusing environment variables and launch arguments. I think @KrauseFx is going to add a default environment variable which can then be used via the preprocessor definition in my earlier comment.

**Comment by KrauseFx** [comment]
@ConfusedVorlon @markusloffler I'm more than happy to add this back to `snapshot`. Let me know if you know how to add this :+1:

**Comment by KrauseFx** [comment]
@ConfusedVorlon Oh I see you already submitted a PR for this: https://github.com/fastlane/snapshot/pull/284/files Thanks :+1:

**Comment by pedro380085** [comment]
Any updates on this?

**Comment by vpolouchkine** [comment]
@pedro380085 Related PR has not been merged yet. https://github.com/fastlane/snapshot/pull/284/files
