### ISSUE TITLE
Screenshot of UIAlertController

### ISSUE THREAD

**Issue by artuan** [fastlane/snapshot#293]
I cannot make screenshot of app with alert controller. This has to do with the "swipe"?!.
Can I do something or should I wait?

Thank you

**Comment by SemenovAlexander** [comment]
+1 for this issue. If I try use snapshot() function  - dialog is being dismissed before actual screenshot is taken

**Comment by SemenovAlexander** [comment]
So, I've ended up with moving swipe gesture to alertcontroller itself instead of target application and now it works fine for me. See pull request #307

**Comment by artuan** [comment]
Thank you @SemenovAlexander, when it will be available an update of snapshot?
