### ISSUE TITLE
snapshot is crashing after successful tests

### ISSUE THREAD

**Issue by foozmeat** [fastlane/snapshot#297]
```
▸ Test Succeeded
sh: line 1: 31981 Segmentation fault: 11  xcodebuild -scheme 'GrayoutUITests' -project './grayout.xcodeproj' -derivedDataPath '/tmp/snapshot_derived/' -destination 'platform=iOS Simulator,id=DF1562AF-6C0A-4DAD-9E30-04C5D6B99A34,OS=9.1' build test
31982 Done                    | tee '/Users/james/Library/Logs/snapshot/Grayout-GrayoutUITests.log'
31983 Done                    | xcpretty
[18:57:59]: Exit status: 139
[18:57:59]: Cought error... 139
```

Sadly, I'm unable to attach a log file. As soon as it throws this error is tries the process over again and the log is truncated.

**Comment by foozmeat** [comment]
Running the command listed above on its own yields no errors.

**Comment by linked67** [comment]
Have this problem too, exit 139 and it try again the same simulator.

**Comment by mihahribar** [comment]
Had the same problem. Removing screenshots folder by hand solved it.

**Comment by pieisgood** [comment]
This has been an issue for me as well. The thing is that snapshot will still pull screenshots from the UITests after the next build. Anyway, the whole unit testing system seems a bit flaky, things will fail when they succeed on screen, loading the app sometimes won't work. A bit frustrating.

**Comment by kylejm** [comment]
I don't know what version of Snapshot you are running, but I just update to version 1.2.2 which fixed the issue :tada:

**Comment by KrauseFx** [comment]
Thanks @kylejm. @foozmeat could you confirm this resolves the issue for you?

**Comment by osrufung** [comment]
Same problem **with 1.4.1** version 
```
Running Tests: [36m[33m>[0m [39;1mTouching[0m CaponateUITests.xctest[0m
[36m[33m>[0m [39;1mTest[0m Succeeded[0m
[36msh: line 1: 28269 Segmentation fault: 11  xcodebuild -scheme 'CaponateUITests' -project '../Caponate.xcodeproj' -derivedDataPath '/tmp/snapshot_derived/' -destination 'platform=iOS Simulator,id=4D625247-19DA-4C07-B81E-DC22CDAFCAD0,OS=9.1' build test[0m
[36m28270 Done                    | tee '/Users/mobimento/Library/Logs/snapshot/Caponate-CaponateUITests.log'[0m
[36m28271 Done                    | xcpretty[0m
[33m>[0m [39;1mBuilding[0m Caponate/Caponate [Debug]
[33m>[0m [39;1mCheck Dependencies[0m
``` 
This happens on a empty *./screenshots* folder, and... yes!, a *headless* configuration. 😔
