### ISSUE TITLE
App Preview automation?

### ISSUE THREAD

**Issue by cannyboy** [fastlane/snapshot#298]
Currently, its not possible to automate uploading App Preview videos using deliver - see https://github.com/fastlane/deliver/issues/34 - due to limitations in Apple's tools - http://www.openradar.me/18426754

However, it would still be useful to be able to automate the creation of App Preview videos using snapshot, using the same UI Test recorded code. Perhaps it is beyond the scope of snapshot.

**Comment by KrauseFx** [comment]
I agree, that would be nice, but currently it's not planned.

**Comment by axaiOS** [comment]
+1

**Comment by artworker** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

artworker@naver.com 님께 보내신 메일 <Re: [snapshot] App Preview automation? (#298)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
