### ISSUE TITLE
VPN IP automation?

### ISSUE THREAD

**Issue by cannyboy** [fastlane/snapshot#299]
I have an app which responds differently according to which country the user is in. This is a result of the server giving the app different things according to the IP of the user. 

I can use GUI apps such as tunnelbear to pretend to be in France, for instance, but is there a recommended way to script this, and have the IP changed according to the language being tested - i.e., when testing Italian, it switched to an Italy IP?

**Comment by KrauseFx** [comment]
You should fake this data somehow, e.g. by accessing the language and showing different content. I wouldn't connect to a different VPN depending on the language of the screenshots.
