### ISSUE TITLE
UI Testing Failure - App failed to quiesce within 30.0s

### ISSUE THREAD

**Issue by ogezue** [fastlane/snapshot#302]
Do you know why this happens? My UITest is running fine from XCode.

Here is my code:

```Objective-C
- (void)setUp
{
    [super setUp];
    self.continueAfterFailure = false;
    
    XCUIApplication* app = [[XCUIApplication alloc] init];
    [Snapshot setLanguage:app];
    [app launch];
}


- (void)testExample
{
    XCUIElementQuery* tabBarsQuery = [[XCUIApplication alloc] init].tabBars;
    [tabBarsQuery.buttons.allElementsBoundByIndex[1] tap];
    [Snapshot snapshot:@"01Overview" waitForLoadingIndicator:NO];
}
```

**Comment by hannesoid** [comment]
Check this https://forums.developer.apple.com/thread/6503
In our case we removed a UIRefreshControl when running tests and it solved it.

**Comment by ogezue** [comment]
Now I know what people mean with test driven design. I don't want to remove UI elements just because the testing can't handle it.

**Comment by bojan** [comment]
Wherever you see the `endRefreshing` method, like in this example:

    refreshControl.endRefreshing()

wrap it like this:

    if self.refreshControl.refreshing {
        self.refreshControl.endRefreshing()
    }

It should do the trick, no need to remove any UI elements.

**Comment by ogezue** [comment]
Added this but error still occurs. Are there any other blocking elements?

**Comment by bojan** [comment]
In our case it was the only point that blocked the UI tests.

This is a clear example of the deteriorating quality of Apple's software. We, the developers, should not be wasting time on tasks like these. :-1:

**Comment by Philluxx** [comment]
I ran into the same issue. After resetting all simulator the error did not occur again. So I tried a lot of things and recognized that it worked when the app was launched the first time in the simulator. It is not deleted automatically after taking screenshots. When I deleted it manually and ran snapshot again, everything was fine again.

Is there an option to remove the app after running snapshot? If I reset simulator each time I have to set local setting again to display the simulator clock and other regional settings in the right format (german)...

**Comment by koenpunt** [comment]
I solved it by adding an extension for `UIRefreshControl`, which is only a member of my test target.

This extension overrides the `beginRefreshing` and `endRefreshing` methods with noop's.

https://gist.github.com/koenpunt/cf8130bdfc432d31136b

**Comment by koenpunt** [comment]
I've updated my gist so that now an internal method of the `UIRefreshControl` is overridden. To make it work you'll have to add a preprocessor flag `TESTING=1` to the configuration you use for your snapshots:

https://gist.github.com/koenpunt/cf8130bdfc432d31136b
