### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by SemenovAlexander** [fastlane/snapshot#314]
This would be very nice to support MacOS app in snapshot as well. 
Now, when Xcode 7 UI testing supports UI Testing on Mac - it should be pretty easy to implement.
How do you think?

**Comment by KrauseFx** [comment]
I agree, this would be a very nice addition to `snapshot`, however requires some changes, in particular how the actual screenshots are triggered.

**Comment by SemenovAlexander** [comment]
@KrauseFx I could try to implement this and create appropriate pull request. I've already performed some experiments, and was able to take some screenshots using same swipe approach as iOS and removing `destination` param from xcodebuild.
However swipe gesture on OSX triggers  menu to open, so it's not very nice. And also not clear for me from code, how to enable "Mac" to be available in devices section. 
Could you give some hint on this points?

**Comment by KrauseFx** [comment]
The devices are detected [here](https://github.com/fastlane/snapshot/blob/master/lib/snapshot/detect_values.rb#L22). Check out the project description on why I used the swipe gesture. If you find a better solution, I'm more than happy to change that in `snapshot`.

**Comment by SemenovAlexander** [comment]
Ok, thanks a lot! Yes, I've already checked description and docs on project couple times to make it clear :) 
I've started to use fastlane couple months ago. We use it for building, delivery and testing our product on iOS, OSX and Android, and really happy with it, so I'll do my best to help solve this issue.
