### ISSUE TITLE
`coordinateWithNormalizedOffset:` not available on AppleTV

### ISSUE THREAD

**Issue by victor** [fastlane/snapshot#315]
I tried to install snapshot for an AppleTV project and followed the instructions to install the helper. But on this platform, `coordinateWithNormalizedOffset:` is not available:

```
#if !TARGET_OS_TV
/*! Creates and returns a new coordinate that will compute its screen point by adding the offset multiplied by the size of the element’s frame to the origin of the element’s frame. */
- (XCUICoordinate *)coordinateWithNormalizedOffset:(CGVector)normalizedOffset;
#endif
```

so there should be another method to trigger the screenshots

**Comment by KrauseFx** [comment]
Mh, I haven't tried `snapshot` on an Apple TV.

I just pushed a new release https://github.com/fastlane/snapshot/releases/tag/1.2.0

I'll try it now :1234:

**Comment by martynovskij** [comment]
not working on Apple TV :(
```
Error setting value '["Apple TV 1080p"]' for option 'devices'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.26.6/lib/fastlane_core/configuration/configuration_file.rb:24:in `eval': Device 'Apple TV 1080p' not in list of available simulators 'iPhone 4s, iPhone 5, iPhone 5s, iPhone 6, iPhone 6 Plus, iPhone 6s, iPhone 6s Plus, iPad 2, iPad Retina, iPad Air, iPad Air 2, iPad Pro' (RuntimeError)
```

**Comment by KrauseFx** [comment]
@victor the new release uses orientation change to generate screenshots
@martynovskij I have the feeling that's `deliver` and not `snapshot`, right?

**Comment by martynovskij** [comment]
@KrauseFx no, it is snapshot (1.2.2)

```
victor$ snapshot
[09:59:29]: Error setting value '["Apple TV 1080p"]' for option 'devices'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.28.0/lib/fastlane_core/configuration/configuration_file.rb:24:in `eval': Device 'Apple TV 1080p' not in list of available simulators 'iPhone 4s, iPhone 5, iPhone 5s, iPhone 6, iPhone 6 Plus, iPhone 6s, iPhone 6s Plus, iPad 2, iPad Retina, iPad Air, iPad Air 2, iPad Pro' (RuntimeError)
```
my Snapfile contain:
```
devices([
  "Apple TV 1080p"
])
```

Also, new release uses orientation change to generate screenshots. But on this platform, ```orientation``` property is not available:
```
Value of type 'XCUIDevice' has no member 'orientation'
```

P.S. Thanks for your work :smile:

**Comment by KrauseFx** [comment]
Ah sorry about that @martynovskij. Sorry, but right now it doesn't seem to be working on tvOS then
