### ISSUE TITLE
Localised string

### ISSUE THREAD

**Issue by Ged2323** [fastlane/snapshot#321]
I had some trouble with a localised string and had to make it not localised so that it would work.  It would cause snapshot to fail when doing the chinese language.

**Comment by jonathanrauch** [comment]
I recently went through a similar issue. Here how I solved it:
* In your UI Tests target -> Build Phases -> Copy Bundle Resources, add the localization files needed (e.g. Localizable.strings).
* Add a function similar to the following:
```swift
func localizedString(key:String) -> String {
/*1*/ let localizationBundle = NSBundle(path: NSBundle(forClass: /*2 UITestsClass*/.self).pathForResource(deviceLanguage, ofType: "lproj")!) 
/*3*/ let result = NSLocalizedString(key, bundle:localizationBundle!, comment: "") // 
    return result
}
/*1 Gets correct bundle for the localization file, see here: http://stackoverflow.com/questions/33086266/cant-get-access-to-string-localizations-in-ui-test-xcode-7 */
/*2 Replace this with a class from your UI Tests 
/*3 Gets the localized string from the bundle */
```
* Then in your code you can use `app.buttons[localizedString("localized.string.key")]`

**Comment by zkirill** [comment]
@jonathanrauch Many thanks! :+1:

**Comment by DominicFrei** [comment]
@jonathanrauch Nice one!

But have ever found a way to do the same with system button?
When I record UITests with Xcode it comes up with something like

```
app.navigationBars["Title"].buttons["Add"].tap()
```

if the language is set to English and 

```
app.navigationBars["Title"].buttons["Hinzufügen"].tap()
```

when set to German for example.

Does anyone see a solution other than localising system button names manually?

**Comment by zkirill** [comment]
@DominicFrei How about we get a shared library going? I localize system button names at the moment and have a few to contribute. Any legal issues?

**Comment by DominicFrei** [comment]
@zkirill Whenever there is a possibility to contribute something for our community, I'm in! :)

What about https://github.com/DominicFrei/iOS_Localised_System_Buttons ?
Sorry I couldn't come up with a better name. :D

**Comment by zkirill** [comment]
@DominicFrei Thank you kindly for setting this up! :+1: Let's hope that others will help.

/cc @egistli @mihahribar @earltedly @b-ray @jilouc Would this be helpful to you?
