### ISSUE TITLE
Just working the first time. Then fails

### ISSUE THREAD

**Issue by vCrespoP** [fastlane/snapshot#325]
Hello, 

I have managed to configure my app for handling snapshot with the latests UI tests and I'm facing this problem. **The first time, everything goes smooth and I got the screenshots, but when it tries to build again and run them again, Error.**

This is the output:

SnapshotTests

✗ testSnapshot, UI Testing Failure - App accessibility isn't loaded

AppUITests.SnapshotTests

testSnapshot, UI Testing Failure - App accessibility isn't loaded

<#PATH#>/SnapshotTests.swift:24

```
        setLanguage(app)
        app.launch()
  ```
	 Executed 1 test, with 1 failure (0 unexpected) in 61.186 (61.188) seconds

[16:17:00]: Exit status: 65
[16:17:00]: Tests failed - check out the log above
/Library/Ruby/Gems/2.0.0/gems/snapshot-1.1.1/lib/snapshot/runner.rb:38:in `work': Tests failed - check out the log above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.1.1/bin/snapshot:37:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.1.1/bin/snapshot:68:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.1.1/bin/snapshot:74:in `<top (required)>'
	from /usr/local/bin/snapshot:23:in `load'
	from /usr/local/bin/snapshot:23:in `<main>'

This is my test file in case it helps:

```
import XCTest

@testable import MainApp

class SnapshotTests: XCTestCase {
        
    override func setUp() {
        super.setUp()
        
        continueAfterFailure = false
       
        let app = XCUIApplication()
        app.launchEnvironment = [ "UITest": "1" ]
        setLanguage(app)
        app.launch()
        
    }
    
    override func tearDown() {
       
        
        super.tearDown()
    }
    
    func testSnapshot() {
        
        let app = XCUIApplication()
        sleep(5)
        snapshot("1Screen")
        app.collectionViews.elementBoundByIndex(0).cells.elementBoundByIndex(3).tap()
        sleep(5)
        snapshot("2Screen")
        app.tables.elementBoundByIndex(0).cells.elementBoundByIndex(0).tap()
        sleep(5)
        snapshot("3Screen")
        app.tables.elementBoundByIndex(0).cells.elementBoundByIndex(1).tap()
        sleep(5)
        snapshot("4Screen")
        
    }
    
}

```

This is my snapfile, just one device, two languages for testing purposes:

```
 devices([
   "iPhone 5"
 ])

languages([
  "en-US",
  "de-DE"
])

scheme <#SCHEME#>

creating new ones

workspace "<#WORKSPACE#>"
```

**Comment by vCrespoP** [comment]
More clues, guys.

If I do the same with just one language and all devices: Working OK.
If I do just one device with language "de-DE": Working OK.

**Comment by vCrespoP** [comment]
With the latest update (1.2.1) it's not working anymore...not even the first time. Everything seems to be working, but when the time for generating the actual files comes:

SnapshotTests
✓ testSnapshot (40.352 seconds)


	 Executed 1 test, with 0 failures (0 unexpected) in 40.352 (40.355) seconds

[10:39:36]: Collecting screenshots...
[10:39:36]: Found 0 screenshots...
[10:39:36]: Looks like the number of screenshots (0) doesn't match the number of names (3)
[10:39:36]: no implicit conversion of nil into String
[10:39:37]: Patching '/Users/.../Library/Preferences/com.apple.iphonesimulator.plist' to scale simulator to 100%

**Comment by Philluxx** [comment]
Can you try to deinstalll your app manually from the simulator and try it again?

See https://github.com/fastlane/snapshot/issues/302#issuecomment-161407019

**Comment by KrauseFx** [comment]
Could you try using the latest versoin?

**Comment by vCrespoP** [comment]
Yes Mr @KrauseFx I will but I don't know when I'll be able, thanks all for your interest. 
Have you encountered any similar behavior in anyone else?

Btw @Philluxx I already try that, even resetting the simulator wiping out everything, restarting Xcode and that kind of things

**Comment by SebastianBoldt** [comment]
Wiping out everything fixed it for me.

**Comment by RobertBiehl** [comment]
For me the issue was solved by preventing ```[[UIApplication sharedApplication] registerForRemoteNotifications]```happening in the simulator. The prompt stuck around unhandled and somehow prevented the next run from happening.

**Comment by ilandbt** [comment]
@RobertBiehl  how did you prevent the registration from happening?

i tried:
``` Swift
        if !NSUserDefaults.standardUserDefaults().boolForKey("FASTLANE_SNAPSHOT") {
            // runtime check that we are in snapshot mode
            
            let type: UIUserNotificationType = [UIUserNotificationType.Badge, UIUserNotificationType.Alert, UIUserNotificationType.Sound];
            let setting = UIUserNotificationSettings(forTypes: type, categories: nil);
            UIApplication.sharedApplication().registerUserNotificationSettings(setting);
            UIApplication.sharedApplication().registerForRemoteNotifications();
        }
```

and 

``` Swift
        if TARGET_IPHONE_SIMULATOR == 0 {
        
            let type: UIUserNotificationType = [UIUserNotificationType.Badge, UIUserNotificationType.Alert, UIUserNotificationType.Sound];
            let setting = UIUserNotificationSettings(forTypes: type, categories: nil);
            UIApplication.sharedApplication().registerUserNotificationSettings(setting);
            UIApplication.sharedApplication().registerForRemoteNotifications();
        }
        
```

non of them worked for me.

**Comment by Vaseltior** [comment]
Hi guys, same issue here.. with *Fastlane* there I get a **exit status 65**

1. When doing so with xcode, I'm getting "Code Coverage Data Generation Failed"... Unable to retrieve the profile data files from 'iPad 2'. The last time the simulator was in use it was set on an iPhone 6 device, and was actually shut down when the test was launched.
2. Ok. Now launching the simulator. Switching from iPhone6 hardware to iPad 2. Leaving the simulator open.
3. Testing! OK (no code coverage error).
4. keep the simulator opened this time on the iPad 2 hardware.
5. *Fastlane* gives always the **exit status 65.**
6. Reset content and settings from the iPad 2 simulator. Leaving the simulator open.
7. *Fastlane* OK.

The problem is I have to do this frequently and have no way to schedule a fastlane lane without expecting an error.

Anyone else has a clue on this? Thx by advance

**Comment by zirinisp** [comment]
Hello,

I am having a similar experience and only with simulator reset I get results. Otherwise on second run I get the following:

`All tests
Test Suite KiteSpotterUITests.xctest started
KiteSpotterUITests
✗ testExample, UI Testing Failure - App failed to quiesce within 30s


KiteSpotterUITests.KiteSpotterUITests
testExample, UI Testing Failure - App failed to quiesce within 30s
/Users/zirinisp/Dropbox/xcode/KiteSpotter/KiteSpotterUITests/KiteSpotterUITests.swift:83
```
        let tablesQuery = app.tables
        tablesQuery.staticTexts["LIVE"].tap()
        self.wait(10)
  ```


	 Executed 1 test, with 1 failure (0 unexpected) in 41.696 (41.703) seconds

[21:56:53]: Exit status: 65
[21:56:53]: Tests failed - check out the log above
[21:56:53]: Backtrace:
`
