### ISSUE TITLE
Test failed. Exit status: 65

### ISSUE THREAD

**Issue by buscarini** [fastlane/snapshot#330]
I upgraded a project from the old UIAutomation method to the new snapshot, and it's not working for me. I get an exit status 65, but there's no visible error above. I am getting a lot of warnings like this:
    Could not resolve external type c:objc(cs)NSString
Which seems to be because of the latest Xcode, and the fact that I have some libraries with precompiled headers, module enabled and such things. If I run the tests in Xcode everything runs fine despite all these warnings.

Any idea how to debug this?

**Comment by vCrespoP** [comment]
Related?

https://github.com/fastlane/snapshot/issues/325

**Comment by pedro380085** [comment]
The same happens here, but only for iPad Air.

**Comment by SebastianBoldt** [comment]
Same error over here. Seems to be random.

**Comment by DominicFrei** [comment]
Same here. Looks totally random at the moment.
Might be a UITest problem though, because the more complicated the tests get the more likely this error occurs.

**Comment by yakubbaev** [comment]
It seems to be somehow related with simulator versions. 
Tested on iOS 9.0, 9.1, 9.2. 
iOS 9.0 appears to be the most stable.

**Comment by appleguy1999** [comment]
Same happens for me. This occurs for me when I call this:
```
func localizedString(key:String) -> String {
	let localizationBundle = NSBundle(path: NSBundle(forClass: EmoticonKeyboardUITests.self).pathForResource(deviceLanguage, ofType: "lproj")!)
	let result = NSLocalizedString(key, bundle:localizationBundle!, comment: "") //
	return result
}
```
(which I got from [Issue #321 comment](https://github.com/fastlane/snapshot/issues/321#issuecomment-159660882))

**Comment by DominicFrei** [comment]
@rcobelli Interesting. I am using the exact same snippet. Might be worth investigating a little bit more.

**Comment by yakubbaev** [comment]
Updating OS from Yosemite to El Capitan fixed issue for me.

**Comment by martingjaldbaek** [comment]
Every time I run snapshot I'm getting "Test failed. Exit status: 65" without even having had the app launched (with a UI Test that runs fine from Xcode). I don't get "Could not resolve external type c:objc(cs)NSString" so at least in my case that's unrelated. The snapshot example project runs fine too. 

What does seem to matter is build time: I've tried invoking xcbuild manually in a couple different ways. If I call
```
xcodebuild -workspace MyProject.xcworkspace -scheme "MyScheme" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' build test
```
then it fails in the same way as when run by snapshot. But if instead I run
```
xcodebuild -workspace MyProject.xcworkspace -scheme "MyScheme" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' test
```
(i.e. don't build before the test) then it actually succeeds. Note that this is when run under El Capitan from a 12" Macbook (1.3GHz), where compiling the app from scratch takes around 5 minutes. So as an experiment I tried running snapshot on another Mac running El Capitan on a quad-core i7, where compiling takes around 30 seconds - and lo and behold, there it works! 

I've read elsewhere about a timeout (120 seconds was referenced there) when connecting to the simulator, which has previously incorrectly including the build time in that timeout, which then caused it to fail on projects that build slowly - it seems like something similar is at play here. It would explain why some people are reporting it sometimes failing and sometimes succeeding, seemingly randomly, if their project's compile time is close to the timeout value, so it sometimes goes over, and sometimes under depending on system load.

If this is the case, then this must be Apple's bug to fix, but in the meantime, I'd like to request a command line option for snapshot to not do the 'build' step first, so there's at least some workaround for those not lucky enough to have a faster computer where the compile time goes below the magic threshold. I've created a fork where I turn the build step into an option that defaults to off and that fixes this issue for me - pull request here: https://github.com/fastlane/snapshot/pull/363 I've turned it to default off since it seems to me that not building is the simplest, and since building can both fix some issues and cause others I'd argue it should be opt-in rather than opt-out (if you disagree, then I guess a version with a --nobuild option is possible too).

**Comment by bitmaskstudio** [comment]
I can reproduce this whenever I have a failing unit test which is included in the test scheme. If I disable unit tests in the test scheme and run UI tests alone it works correctly. Weird though as it just started happening, the unit tests failures never used to effect the UI tests screenshots.

**Comment by DominicFrei** [comment]
@bitmaskstudio @KrauseFx Would you recommend using a separate scheme only for snapshot then?

**Comment by iOSAppMaker** [comment]
Have the same problem. Damn slow, doesn't load anything. And finally shows this: 
Exit status: 65

**Comment by iOSAppMaker** [comment]
I can do unit testing when I try from xcode. But somehow fails when I try running snapshot from terminal. 
It gets stuck at "Checking Dependancy". Sometimes it compiles further, but always stops short of the app running in the simulator.

**Comment by iOSAppMaker** [comment]
Here is the error post: 
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.0/lib/fastlane_core/command_executor.rb:26:in `each': Interrupt
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.0/lib/fastlane_core/command_executor.rb:26:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.0/lib/fastlane_core/command_executor.rb:25:in `spawn'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.0/lib/fastlane_core/command_executor.rb:25:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:120:in `launch'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:35:in `block (3 levels) in work'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:31:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:31:in `block (2 levels) in work'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:30:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:30:in `block in work'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:29:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:29:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/actions/snapshot.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:382:in `block (4 levels) in parsing_binding'
	from Fastfile:360:in `each'
	from Fastfile:360:in `block (3 levels) in parsing_binding'
	from Fastfile:354:in `open'
	from Fastfile:354:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:51:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/bin/fastlane:37:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/bin/fastlane:155:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/bin/fastlane:161:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by iOSAppMaker** [comment]
I noticed that when I delete the builds from the simulator and re-runs them, then they continue a bit more, and exits with error status:  
```
Testing failed:
Test target <AppName>UITests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **
[15:45:27]: Exit status: 65
```

I runned without anything in UITests to make sure it is not an error because of some wrong programming code. 

Full code: 

```
Testing failed:
Test target Morse GuruUITests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **
[15:45:27]: Exit status: 65
[15:45:28]: Tests failed - check out the log above
[15:45:28]: Backtrace:
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/error_handler.rb:14:in `handle_test_error'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:126:in `block in launch'
	/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.0/lib/fastlane_core/command_executor.rb:61:in `call'
	/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.0/lib/fastlane_core/command_executor.rb:61:in `execute'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:120:in `launch'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:35:in `block (3 levels) in work'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:31:in `each'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:31:in `block (2 levels) in work'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:30:in `each'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:30:in `block in work'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:29:in `each'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:29:in `work'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/actions/snapshot.rb:17:in `run'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:127:in `chdir'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:127:in `execute_action'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	Fastfile:382:in `block (4 levels) in parsing_binding'
	Fastfile:360:in `each'
	Fastfile:360:in `block (3 levels) in parsing_binding'
	Fastfile:354:in `open'
	Fastfile:354:in `block (2 levels) in parsing_binding'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/lane.rb:36:in `call'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/lane.rb:36:in `call'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:51:in `block in execute'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:46:in `chdir'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:46:in `execute'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/bin/fastlane:37:in `block (2 levels) in run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/bin/fastlane:155:in `run'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/bin/fastlane:161:in `<top (required)>'
	/usr/local/bin/fastlane:23:in `load'
	/usr/local/bin/fastlane:23:in `<main>'
```

But it doesn't exit here. Instead it does the run for the next language, runs upto "checking dependency", and then stands there stuck, and then I have to exit using Control+C. When it exits, it shows the previous error of "Exit status 65".

**Comment by iOSAppMaker** [comment]
Do I need to include all the App Target Class into Unit Test Target?? Testing the app from Xcode shows no problem and runs smooth. The problem appears only when running snapshot (from terminal).

**Comment by iOSAppMaker** [comment]
Sma epost in fastlane_core issues: 
https://github.com/fastlane/fastlane_core/issues/65#event-505068508

**Comment by iOSAppMaker** [comment]
There was no problem with UIAutomation.

**Comment by iOSAppMaker** [comment]
It might be a time out problem, I found out that small apps are running properly, but bigger ones stop at the point I mentioned.

**Comment by iOSAppMaker** [comment]
I got this in a recent run: 
2016-01-08 02:15:02.185 xcodebuild[9954:203428]  iPhoneSimulator: Timed out waiting 120 seconds for simulator to boot, current state is 1.
