### ISSUE TITLE
Test location defined in scheme settings does not work when running snapshot

### ISSUE THREAD

**Issue by Myrronth** [fastlane/snapshot#333]
I have a location-based app that has to show map(s) on its app store screenshots using a custom "current" location. To achieve this I created a custom scheme "Snapshot" and set a gpx file as test location for the tests that snapshot will use to create its screenshots.

When running the test with XCode via Product > Test the "current" lcoation is set to the location provided by the gpx file and all is working like expteced.

But when running the test with snapshot (I would assume snapshot does the same that I do via the interface?) than the simulator has no current location and my maps are messed up.

Does anyone know why this is not working and can provide me with a solution or a workaround?

**Comment by Ashton-W** [comment]
If you run the UI tests via xcode-build does the same thing happen?
Running snapshot with verbose should print out the xcodebuild command ised

**Comment by Myrronth** [comment]
snapshot uses "xcrun xcodebuild -showBuildSettings -workspace './Grunzeug.xcworkspace' -scheme 'Snapshot'" to run the tests. I don't know if there is another way to run the tests manually from the command line? The specified scheme and workspace seems to be correct and the rest of the tests itself succeed.

I attached a screenshot of my scheme's test configuration if that helps in some way?

![screen shot 2015-12-04 at 14 56 06](https://cloud.githubusercontent.com/assets/75341/11591389/9815841e-9a97-11e5-9ff3-c343c7146c51.png)

**Comment by Ashton-W** [comment]
Try 
`xcrun xcodebuild -workspace './Grunzeug.xcworkspace' -scheme 'Snapshot' test`


If you have time, could you create a small sample project that reproduces it?

**Comment by Myrronth** [comment]
Sorry for the delayed response, i had a few busy weeks.

I created a small test project (https://github.com/Myrronth/GPX-Location/tree/master).

Running and testing the app via Xcode works fine, testing via snapshot or `xcrun xcodebuild -scheme 'GPX Location' -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' test` does not.

**Comment by sanmarcos** [comment]
Same issue here

**Comment by ClementPadovani** [comment]
Hey @Myrronth, I’ve had the same issue as you. After some digging in the Apple private frameworks I’ve abandoned the GPX file for my tests. I’m using a location simulation class that’s available as a private API. You can check it out [here](https://github.com/ClementPadovani/aBike/blob/master/aBikeFramework/aBikeLibrary/Additions/VELocationManager.m#L195).

**Comment by Ashton-W** [comment]
@KrauseFx can we label this issue and future issues like these as *Xcode Issues*?

**Comment by Ashton-W** [comment]
I think this is related to this Xcode Known Issue, since Gather Coverage data is another flag set in schemes that does not work during UI Testing:

> Code coverage analysis is not recorded for the target app when UI tests are executed via
xcodebuild test, even when "Gather coverage data" is enabled. (23913271)

**Comment by sanmarcos** [comment]
![screen shot 2016-01-27 at 21 34 45](https://cloud.githubusercontent.com/assets/229094/12648059/f39956d8-c58c-11e5-83a6-a152fa94ef6a.png)

Xcode does support location testing with UI Testing.

They do not work in Snapshot.

Perhaps somebody can figure out what exactly Xcode is doing to launch a simulator instance with location simulation.

**Comment by Ashton-W** [comment]
In my brief testing it does not work when running UI Tests at all.

**Comment by sanmarcos** [comment]
It works if you don't run it with a UI Test that has any reference to snapshot. Also be sure to reset the simulator before trying it again.

**Comment by ClementPadovani** [comment]
You can simulate your location using this method that I specified in this comment https://github.com/fastlane/snapshot/issues/333#issuecomment-172812854

**Comment by olutsenko** [comment]
I have the same issue.

Location simulation works if running tests from Xcode (cmd+U).
Location simulation doesn't work when running 'snapshot' command.

**Comment by olutsenko** [comment]
As a workaround this helps me.

Make sure your simulator is set to use custom location manually before running 'snapshot'. You do it once (not for each supported simulator).

![screen shot 2016-02-17 at 17 51 34](https://cloud.githubusercontent.com/assets/303121/13117313/b39b228c-d59f-11e5-845b-6500981df9a7.png)
