### ISSUE TITLE
Image Quality of Screenshots

### ISSUE THREAD

**Issue by talkaboutdesign** [fastlane/snapshot#339]
When my screenshots get uploaded to the app store the quality is significantly lower then that of screenshots I take and upload manually. What could be possibly causing this?

**Comment by simonmaddox** [comment]
I've found this happens when you zoom the simulator to a smaller size. Leave it at full size, and the screenshot quality is much better.

**Comment by KrauseFx** [comment]
The latest version of `snapshot` should automatically zoom the simulator to a 100%. Is that not the case for you?
