### ISSUE TITLE
Reset Simulators + Add iPad Pro

### ISSUE THREAD

**Issue by valeIT** [fastlane/snapshot#353]
I'm resetting all simulators before running snapshot each time, because Xcode always breaks something.
Doing so doesn't add the iPad Pro.
```
[17:47:30]: Error setting value '["iPhone 6", "iPhone 6 Plus", "iPhone 5", "iPhone 4s", "iPad Retina", "iPad Pro"]' for option 'devices'

Device 'iPad Pro' not in list of available simulators 'iPhone 4s, iPhone 5, iPhone 5s, iPhone 6, iPhone 6 Plus, iPhone 6s, iPhone 6s Plus, iPhone 6s Plus + watch, iPad 2, iPad Retina, iPad Air, iPad Air 2'
```

Can i add the iPad Pro from the FastFile or manually from a shell script or something?

**Comment by KrauseFx** [comment]
So it's a bug in `snapshot reset_simulator`, right?

**Comment by valeIT** [comment]
Yes, it would appear so.
