### ISSUE TITLE
(RuntimeError) How to get rid of this?

### ISSUE THREAD

**Issue by ashukhobragade** [fastlane/snapshot#357]
/Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:49:in `work': Tests failed - check out the log above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/bin/snapshot:37:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/bin/snapshot:78:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/bin/snapshot:84:in `<top (required)>'
	from /usr/bin/snapshot:23:in `load'
	from /usr/bin/snapshot:23:in `<main>'
logout

**Comment by KrauseFx** [comment]
This basically means, that your UI Tests have failed and didn't succeed.

**Comment by KrauseFx** [comment]
That's why you get an error

**Comment by ashukhobragade** [comment]
Could not write domain /Users/ashishk/Library/Preferences/

How could I make it write?

**Comment by wenyang9319** [comment]
✗ testRoamingSearch, UI Testing Failure - No matches found for SearchField
** TEST FAILED **



MyMaxisUITests.RoamingUITest
testRoamingSearch, UI Testing Failure - No matches found for SearchField
/Users/macserver/Desktop/Developments/MyMaxis/maxis-mymaxis-ios/MyMaxisUITests/RoamingUITest.swift:27
```
        let referenceSearchText = app.tables.staticTexts.elementAtIndex(1).label
        roamingSearchField.tap()
        roamingSearchField.typeText(referenceSearchText)
  ```


	 Executed 2 tests, with 1 failure (0 unexpected) in 55.452 (55.463) seconds

[12:08:32]: Exit status: 65
[12:08:32]: Tests failed - check out the log above

+----------+---------+
|  snapshot results  |
+----------+---------+
| Device   | en-US   |
+----------+---------+
| iPhone 5 |  ❌      |
+----------+---------+

/Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:49:in `work': Tests failed - check out the log above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/bin/snapshot:37:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/bin/snapshot:78:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/bin/snapshot:84:in `<top (required)>'
	from /usr/bin/snapshot:23:in `load'
	from /usr/bin/snapshot:23:in `<main>'

I am also facing this issue, this problem occur in one of my mac pc.
Same situation applied for another Mac, it got no issues to run snapshot, it would still capture the other screenshot even the test failed. The failed test case wouldn't capture anythings.

Both Mac behave differently, is it my problem? If answer is yes, how can i solve this?
