### ISSUE TITLE
No such file or directory - screenshots/screenshots.html

### ISSUE THREAD

**Issue by ilteris** [fastlane/snapshot#360]
Hello, 

Great set of tools! Thanks so much for building this for the community. I am using snapshot. I managed to make it work however I haven't managed it to generate screenshots.  My test class and results are below.

https://gist.github.com/ilteris/e92a48e154280f23a64b

        [14:05:49]: > ▸ Test Succeeded
        [14:05:49]: > All tests
        [14:05:49]: > Test Suite DevUITests2.xctest started
        [14:05:49]: > DevUITests2
        [14:05:49]: > ✓ testExample (4.182 seconds)
        [14:05:49]: >    Executed 1 test, with 0 failures (0 unexpected) in 4.182 (4.184) seconds
        [14:05:49]: >
        [14:05:49]: Collecting screenshots...
        [14:05:49]: Found 0 screenshots...

        +---------------+-------+-------+-------+
        |           snapshot results            |
        +---------------+-------+-------+-------+
        | Device        | en-US | de-DE | it-IT |
        +---------------+-------+-------+-------+
        | iPhone 4s     |  💚    |  💚    |  💚    |
        | iPhone 5      |  💚    |  💚    |  💚    |
        | iPhone 6      |  💚    |  💚    |  💚    |
        | iPhone 6 Plus |  💚    |  💚    |  💚    |
        | iPad Retina   |  💚    |  💚    |  💚    |
        +---------------+-------+-------+-------+

        [14:05:49]: Generating HTML Report
        /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/reports_generator.rb:34:in `write': No such file or directory - screenshots/screenshots.html (Errno::ENOENT)
        from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/reports_generator.rb:34:in `generate'
        from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:52:in `work'
        from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/bin/snapshot:37:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/bin/snapshot:78:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/bin/snapshot:84:in `<top (required)>'
        from /usr/local/bin/snapshot:23:in `load'
        from /usr/local/bin/snapshot:23:in `<main>'

Am I missing something here? Thanks so much!

**Comment by KrauseFx** [comment]
This this start happening recently?

**Comment by ilteris** [comment]
@KrauseFx I cannot answer for before since I didn't try the library before but it happened yesterday.

**Comment by bitmaskstudio** [comment]
I get the same error, 

[16:12:08]: Collecting screenshots...
[16:12:09]: Found 0 screenshots...

+---------------+-------+-------+-------+
|           snapshot results            |
+---------------+-------+-------+-------+
| Device        | en-US | de-DE | it-IT |
+---------------+-------+-------+-------+
| iPhone 4s     |  💚    |  💚    |  💚    |
| iPhone 5      |  💚    |  💚    |  💚    |
| iPhone 6      |  💚    |  💚    |  💚    |
| iPhone 6 Plus |  💚    |  💚    |  💚    |
| iPad Retina   |  💚    |  💚    |  💚    |
+---------------+-------+-------+-------+

[16:12:09]: Generating HTML Report
[16:12:09]: Variable Dump:
[16:12:09]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
[16:12:09]: No such file or directory - fastlane/screenshots/screenshots.html

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 19          |
| 4    | snapshot                            | 883         |
+------+-------------------------------------+-------------+

[16:12:09]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
✨  Once crash reporting is enabled, you get a clean output when something goes wrong.
🙊  More information about privacy: https://github.com/KrauseFx/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/reports_generator.rb:34:in `write': No such file or directory - fastlane/screenshots/screenshots.html (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/reports_generator.rb:34:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.4.2/lib/snapshot/runner.rb:52:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/actions/snapshot.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:36:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:51:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/bin/fastlane:37:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/bin/fastlane:155:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/bin/fastlane:161:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
