### ISSUE TITLE
How do I can make it write? I am always getting this error every time I run the snapshot

### ISSUE THREAD

**Issue by ashukhobragade** [fastlane/snapshot#362]
Could not write domain /Users/ashishk/Library/Preferences/com.apple.iphonesimulator.plist; exiting

**Comment by KrauseFx** [comment]
How do you run `snapshot`? SSH? Jenkins?

**Comment by ashukhobragade** [comment]
In Mac terminal

On Jan 13, 2016 4:01 AM, Felix Krause <notifications@github.com> wrote:

How do you run snapshot? SSH? Jenkins?

**Comment by ashukhobragade** [comment]
In Mac terminal

**Comment by ddilley** [comment]
No response? I have the same issue.

**Comment by vpolouchkine** [comment]
Are you still hitting this? Can you share your setup details please?

**Comment by jeffreyjackson** [comment]
I am also seeing this issue

**Comment by i2amsam** [comment]
@jeffreyjackson could you share your setup details?  Specifically, could you see if `~/Library/Preferences/com.apple.iphonesimulator.plist` exists and who the owner is?  E.g.

```
ls -lah ~/Library/Preferences/com.apple.iphonesimulator.plist
```

and also the version of XCode are you running?  It looks like the error is coming from trying to apply the [zoom fix](https://github.com/fastlane/snapshot/blob/master/lib/snapshot/fixes/simulator_zoom_fix.rb#L10)
