### ISSUE TITLE
Device starts in other language than app

### ISSUE THREAD

**Issue by senfi** [fastlane/snapshot#365]
It seems, as this is not intended: https://twitter.com/senfi/status/678921936848740352

I checked out the repository including the example project. The Snapfile was changed at the devices- and the languages-part:
```
 devices([
   "iPhone 6",
 ])

languages([
  "en-US",
  "de-DE",
])
```
If i run ```snapshop``` on this project, this is the displayed run config:
```
+----------------------------+-------------------------+
|              Summary for snapshot 1.4.2              |
+----------------------------+-------------------------+
| project                    | ./Example.xcodeproj     |
| devices                    | ["iPhone 6"]            |
| languages                  | ["en-US", "de-DE"]      |
| launch_arguments           | [""]                    |
| output_directory           | screenshots             |
| ios_version                | 9.2                     |
| stop_after_first_error     | false                   |
| skip_open_summary          | false                   |
| clear_previous_screenshots | false                   |
| reinstall_app              | false                   |
| buildlog_path              | ~/Library/Logs/snapshot |
| clean                      | false                   |
| scheme                     | ExampleUITests          |
+----------------------------+-------------------------+
```
The results are good:
```
+----------+-------+-------+
|     snapshot results     |
+----------+-------+-------+
| Device   | en-US | de-DE |
+----------+-------+-------+
| iPhone 6 |  💚    |  💚    |
+----------+-------+-------+
```

But it seems like, the simulator device is not started with the same language as the app. When running the app in de-DE-locale, the Simulator remains in device-default en-US-locale. See the two attached snapshots: both show ```7:47 AM``` in the statusbar, but given a german locale it should be without the am and the ```Carrier``` should be a ```Netzbetreiber```.

![iphone6-0launch](https://cloud.githubusercontent.com/assets/806859/11972250/ef38c72c-a949-11e5-827a-8d3b9ece0e94.png)
![iphone6-0launch](https://cloud.githubusercontent.com/assets/806859/11972255/f63dac2c-a949-11e5-9ab9-3bc51f35249d.png)

The app is perfectly started with the correct language.

I am using Version 7.2 (7C68) on El Capitan 10.11.2 (15C50). 
```
$ snapshot --version
snapshot 1.4.2
```

If i can provide any more information, just let me know.

**Comment by Alak** [comment]
+1

**Comment by buhlem** [comment]
I also have the same issue, any solution ?

**Comment by KrauseFx** [comment]
I don't know if it's possible to set the simulator locale. Instead the language is passed via launch arguments to your app
