### ISSUE TITLE
Hardware keyboard connected

### ISSUE THREAD

**Issue by ldrr** [fastlane/snapshot#367]
Hello Felix,

when the simulator is connected to a hardware keyboard ("Hardware / Keyboard / Connect hardware keyboard") it's not possible to set the text from a password field. The following code will fail

```
    XCUIApplication *app = [[XCUIApplication alloc] init];
    XCUIElement *passwordSecureTextField = app.secureTextFields[@"password"];
    [passwordSecureTextField tap];
    [passwordSecureTextField typeText:@"verySecurePassword"];
```

That's not an snapshot issue per se but it would be very cozy to have an option to disconnect the hardware keyboard.

Christoph

**Comment by KrauseFx** [comment]
:+1:
