### ISSUE TITLE
Use two sets of devices in snapshot? (Or have multiple Snapfiles?)

### ISSUE THREAD

**Issue by RainerSchwarze** [fastlane/snapshot#376]
I'm using fastlane snapshot for building the screenshots for the App Store. As usual the set of devices is defined in the `./fastlane/Snapfile`. Now I want a different set of screenshots for a website and do not want all the devices, but only one of them.

So far I defined two lanes in `./fastlane/Fastfile` where one `snapshot` overrides the `devices` like so:

      desc "Just run snapshot"
      lane :mysnapshot do
        snapshot
      end
    
      desc "Just run snapshot for one device only"
      lane :mysnapshot2 do
        snapshot(
          devices: ["iPhone 5"]
        )
      end

I'm fine with this, but is there a solution only using the `Snapfile` or using two snapfiles?

(Can I specify the `Snapfile` to use with the `snapfile` command? - From what I see, this is not possible.)

----
Regarding the "underlying problem":

So far I have two targets for UITests. One for the UI tests and one for the screenshots. To run the screenshot UI tests, I created a second scheme which only runs that target. To make the other set of screenshots for the website, I intend to pass information with `launch_arguments`. Depending on those, one or the other set of tests will be run in the screenshots target. Does that sound reasonable or is there a much better way to do this?

(cross posted - question is also at http://stackoverflow.com/q/34618777/1396265)

**Comment by wkoszek** [comment]
@RainerSchwarze With Ruby-based stuff like `snapshot` and other fastlane tools, you can pick the different configurations of things based on something like environment variable, for example. If `ENV['WEBSITE_BUILD']` is there, you pick a different list of devices.

**Comment by RainerSchwarze** [comment]
@wkoszek Thanks for the hint. Indeed - every now and then I forget, that things like `Snapfile` are just ruby code instead of only a text config file.

**Comment by KrauseFx** [comment]
Easiest way is probably to use fastlane and define 2 lanes for each of the configurations. You can pass the devices, languages and more to each of the `snapshot` calls there. Let me know if that works for you.

There is no way to specify the `Snapfile` right now.
