### ISSUE TITLE
Is it not possible to take screenshots even if the tests fail ? 

### ISSUE THREAD

**Issue by gop1334** [fastlane/snapshot#384]
Looks like currently we can get screenshots only when all tests pass. We have around 100s of tests and we are using snapshot to take screenshots at different points in the tests. Is there an option to generate the screenshots if some of the tests fail ?

**Comment by gop1334** [comment]
Hi @KrauseFx - Is this possible ? Right now snapshot is working great for us when all tests pass. However if even one single test fails we don't get the screenshots.

**Comment by KrauseFx** [comment]
Sorry no, the tests have to pass
