### ISSUE TITLE
how to get Screenshots in multitarget projects

### ISSUE THREAD

**Issue by ashukhobragade** [fastlane/snapshot#391]
I am having  multitarget project and when I add UItest target and added an executable app for it.
To get the screenshot for new target,  I am just changing executable app for UItest but it keeps on running for a long time and UItest gets fails

Do you have other solution for multi targets?

**Comment by ashukhobragade** [comment]
Any solution for this ?

**Comment by vpolouchkine** [comment]
Take a look at https://github.com/fastlane/snapshot/issues/348 for a possible solution.
