### ISSUE TITLE
How to fix error - Undeclared Identifier Snapshot for Objective-C Project?

### ISSUE THREAD

**Issue by varmeh** [fastlane/snapshot#397]
The swift.h file created by XCode holds no reference to snapshot.

**Comment by vpolouchkine** [comment]
Did you add the helper and bridge files per https://github.com/fastlane/snapshot#quick-start?

**Comment by varmeh** [comment]
I did.

**Comment by zauberware** [comment]
Following solution worked for me:

1. Change "class Snapshot: NSObject" to "@objc class Snapshot: NSObject" in SnapshotHelper.swift
2. Change the build settings of your test target (not the normal project). Set "Install Objective-C Compatibility Header" to YES.
3. Clean and build, you should now have a bridge file in your derived data (not in your project).
4. The bridge file is not added to your project but only to the derived data. Sometimes with a different name than expected and then the import doesn't work. To find it go to XCode-->Window-->Projects, click on the arrow right beside your derived data folder. Finder opens, then search for Swift.h and you will find your bridge file. Import that into your testcase-class via "#import "NameOfYourBridgeFile-Swift.h".

Hope that helps!

**Comment by varmeh** [comment]
Hey Zuber, sorry for delayed response.
I tried all this and it still did not work for me.
Derived header did not have the implementation of snapshot class (checked in derived data folder).
That's why it's still not working for me.

**Comment by cguess** [comment]
I'm fighting with the same issues here. @zauberware I've gone through every step you've laid out and Snapshot still cannot be found in my test files as a class. Any ideas?

**Comment by zauberware** [comment]
Hi @cguess ,

could you get to step 3 to generate the bridge file in the derived data?
If not you can try to delete and add the UI target again. I had to change the valid target architectures in the build settings of the UI target and the product name to generate the bridge file.

Hope that helps!

Marcus
