### ISSUE TITLE
Can Snapshot be used in XCode Unit Tests? (not UI Automation tests?)

### ISSUE THREAD

**Issue by jtwigg** [fastlane/snapshot#398]
I'm really finding im leveraging the use cace that  ios-snapshot-test-case provides for
https://github.com/facebook/ios-snapshot-test-case.git
but I really like the overall pattern that snapshot provides, 
BUT 
I find UI Automation tests to be not very helpful in Xcode. I prefer to mock a bit of data and render to disk what it would look like. This is not easily doable with UI Automations at all.

Question : Can I take snopshots of raw View's in a Unit Test?

**Comment by vpolouchkine** [comment]
No, not at this time.
