### ISSUE TITLE
FASTLANE_SNAPSHOT should only be set when running Snapshot

### ISSUE THREAD

**Issue by Ashton-W** [fastlane/snapshot#404]
Currently Snapshot sets the userDefault value `FASTLANE_SNAPSHOT` to YES when your tests call `setupSnapshot:`, even if you are running the UI Tests through Xcode. 

Shouldn't this only be set when the UI Tests are actually being run from Snapshot? Or does that introduce too much unpredictable behaviour into the tests?

**Comment by KrauseFx** [comment]
Agreed, it should only be set when running it via `snapshot`

**Comment by Ashton-W** [comment]
@KrauseFX this would have to be done via the temporary file, but we would need to clear it at the end of snapshot because the tests will read that file regardless of being run by snapshot or not. Do you see a problem with this approach?

**Comment by KrauseFx** [comment]
Is it still a pre-processor macro then? You need to be able to actually access this value in code

**Comment by Ashton-W** [comment]
It is a key in `NSUserDefaults`
