### ISSUE TITLE
Snapshot- Code is executing but no snapshot are taken

### ISSUE THREAD

**Issue by sam-swift** [fastlane/snapshot#408]
I have downloaded the project from this path and configured it.

1. Executed "sudo gem install snapshot" in terminal
2. Executed  "xcode-select --install" in terminal
3. Navigate to "snapshot_test" folder in terminal and executed the commend "snapshot init" ,  
SnapshotHelper.swift and snapfile are created.
4.  I have added "screenshot" and "fastlane/screenshot" folder under "Snapshot TestUITests" folder.
5. My snapshot function looks like:
```
    class func snapshot(name: String, waitForLoadingIndicator: Bool = false) {
        if waitForLoadingIndicator {
            waitForLoadingIndicatorToDisappear()
        }

        print("snapshot: \(name)") 

        sleep(1)
        XCUIDevice.sharedDevice().orientation = .Unknown
print("After-snapshot: \(name)")
 }
```
6.I have used this function to take screenshots in tests using "snapshot run". In console "screenshot: snap1" and "After-snapshot:snap1" are displayed but no screenshot is displayed with name "snap1.jpg" in any of "screenshot" and "fastlane/screenshot"
folders.

screenshot version 1.4.4

Please let me know if I am missing anything, as per my understanding "snapshot" code is executing successfully but no screenshot is these. Need your help to solve this issue, as I stuck with this from long time.

**Comment by vpolouchkine** [comment]
Are you still running into this? If so, can you please update and try again?
