### ISSUE TITLE
Screenshot and html report are not generated when tests failed

### ISSUE THREAD

**Issue by mwang2016** [fastlane/snapshot#424]
I have installed fastlane and snapshot:
 - sudo gem install fastlane
- fastlane enable_crash_reporting
- sudo gem install snapshot
- xcode-select --install
- snapshot init

Everything works fine when all the tests passed. Screenshot were taken and html report were generated.
However, if the some tests failed no screenshots and html generated. What I would like to do is to get screenshots report when tests failed so user can see what was the issue. Is this behaviour normal or I have missed anything? 

Here are the errors I got:

+---------------+---------+
|    snapshot results     |
+---------------+---------+
| Device        | en-US   |
+---------------+---------+
| iPhone 6      |  ❌      |
| iPhone 6 Plus |  💚      |
+---------------+---------+

Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'bc4d16430032d57997af92d937bc52dc'
The crash report has been stored locally '/tmp/sentry_bc4d16430032d57997af92d937bc52dc.json'
/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:49:in `work': [!] Tests failed - check out the log above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/bin/snapshot:37:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/bin/snapshot:78:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/bin/snapshot:84:in `<top (required)>'
	from /usr/local/bin/snapshot:23:in `load'
	from /usr/local/bin/snapshot:23:in `<main>'

**Comment by KrauseFx** [comment]
Yes, the HTML page is only generated when all screenshots succeeded.

**Comment by mwang2016** [comment]
Hi Krause,

Thanks for the quick reply. Is it possible to get it generated even if the test failed? I can make some changes on my side just for this special needs, however I would like to know where should I look up.

**Comment by KrauseFx** [comment]
Basically the report gets generated here: https://github.com/fastlane/snapshot/blob/master/lib/snapshot/runner.rb#L52
If you use fastlane, it is quite easy to generate the report yourself, you should be able to add this to your `Fastfile`:

```ruby
Dir.chdir("..") do
  require 'snapshot'
  ReportsGenerator.new.generate
end
```
if that doesn't work, try it without the `Dir.chdir` :+1:

**Comment by mwang2016** [comment]
Hi Krause,

Thank you for the help. It does get better, the report was generated when test failed. But some screenshots were not taken in the failed test case. Here's one of my functions for validating the result:
    func verifyStaticTextsVisible(texts: String) {
        let text = app.staticTexts[texts]
        if !text.exists{
            snapshot(texts+self.currentTimeStamp())
            XCTFail("ERROR:  Static text: \"\(text)\" does not exist on the screen.")
        }
    }
If the text does not exist, I should take screenshot. But the snapshot did not work at this point. Is it because there was no action happened during that moment? I was thinking to write some program to capture UIView and export the image files to the output_directory. Do you think that will work? Or there should be some better ways.
