### ISSUE TITLE
Snapshot hangs on Running tests: Touching target.xctest

### ISSUE THREAD

**Issue by bb-git** [fastlane/snapshot#427]
There is just nothing happening at all. Earlier this day it was running, but now it just stopped working. What can I do?

Stack Trace on canceling shows this:
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.1/lib/fastlane_core/command_executor.rb:47:in `each': Interrupt
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.1/lib/fastlane_core/command_executor.rb:47:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.1/lib/fastlane_core/command_executor.rb:46:in `spawn'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.1/lib/fastlane_core/command_executor.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:119:in `launch'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:35:in `block (3 levels) in work'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:31:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:31:in `block (2 levels) in work'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:30:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:30:in `block in work'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:29:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:29:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/actions/snapshot.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:38:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/bin/fastlane:150:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.57.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by i2amsam** [comment]
Appears that it is have trouble starting the simulator @bb-git, have you tried quitting / restarting the simulator and XCode?

**Comment by martnst** [comment]
@i2amsam thx, this worked for me.
