### ISSUE TITLE
No way to suppress build output

### ISSUE THREAD

**Issue by corristo** [fastlane/snapshot#434]
Log after making snapshots for 6 languages on 4 devices takes approximately 20 Mb for me and contains mostly xcodebuild output. It would be nice to have an option to suppress it.

**Comment by i2amsam** [comment]
@corristo could you clarify which log file is 20 mb?  Thanks!

**Comment by corristo** [comment]
@i2amsam one stored by Jenkins for each build. Sorry, I forgot to mention that.

**Comment by KrauseFx** [comment]
The output shouldn't be `xcodebuild` output, but `xcpretty` formatted output that doesn't take up so much space
