### ISSUE TITLE
Unable to import/use SnapshotHelper.swift in Objective-C project

### ISSUE THREAD

**Issue by DipenPanchasara** [fastlane/snapshot#441]
I configured snapshot and generated SnapshotHelper.swift, added it to my Test Target and writing following code in Test.m file throws error

    XCUIApplication *app = [[XCUIApplication alloc] init];
    [Snapshot setupSnapshot:app];
    [app launch];

error : FastlaneDemoUITests.m:33:6: Use of undeclared identifier 'Snapshot'

It doesn't create ProductModule Header. 
#import "FastlaneDemo-Swift.h" 
It also throws `FastlaneDemoUITests.m:11:9: 'FastlaneDemo-Swift.h' file not found`

XCode : 7.2
Defines Module : YES
Product Module Name : FastlaneDemoUITests

kindly advise what to do?

**Comment by dermaaarkus** [comment]
you can write your uitests also in swift, for me it was much easier althoug my app code is objective c
