### ISSUE TITLE
Keyboard isn't localized

### ISSUE THREAD

**Issue by MuscleRumble** [fastlane/snapshot#449]
This issue might be a duplicate of #4 and/or #131, but I'm not sure if it's just something that I'm doing wrong. I'm using Xcode 7.2.1 with UI testing and taking screenshots in English and German. I don't know what the cause is, but I always see the German keyboard, when running snapshot. Is it possible to set the right keyboard language automatically?

**Comment by KrauseFx** [comment]
Yeah, the thing is that `snapshot` can only set the language of the app, not the simulator.
