### ISSUE TITLE
Create screenshots in parallel on multiple devices?

### ISSUE THREAD

**Issue by ffittschen** [fastlane/snapshot#450]
This weeks [iOS Dev Weekly (Issue 238)](https://iosdevweekly.com/issues/238?#tools) featured a [Parallel iOS Simulator Testing](https://github.com/plu/parallel_ios_tests) tool to run UI Tests on multiple simulator instances.

I was wondering if this could be applied to `snapshot` to reduce the time it takes to create screenshots even more?

**Comment by bartoszj** [comment]
Hi,

According to the `xctool` [issue](https://github.com/facebook/xctool/issues/534) UIAutomations is not supported. Only the logic tests and application tests are working. Also I've tried to run test "manually" according to the [Parallel iOS Simulator Testing](https://github.com/plu/parallel_ios_tests) and I can confirm that UI Tests are not executed at all. Unfortunately we have to wait until `xctool` starts working with UI Automation or `xcodebuild` to start working with multiple simulators.

**Comment by KrauseFx** [comment]
This would probably require some additional things to distinguish between the devices when looking at the generated files, but should work. This would also be interesting for [scan](https://github.com/fastlane/scan)
