### ISSUE TITLE
Simulator language not working after update.

### ISSUE THREAD

**Issue by freynolds** [fastlane/snapshot#469]
Just updated to 1.9.0
My snapfile has 

languages([
  "es-ES"
])

And only 1 of the 6 simulators started in Spanish, the rest started in english (although logs indicated the contrary)
`[14:46:29]: ------------------------
[14:46:29]: --- iPad Pro - es-ES ---
[14:46:29]: ------------------------`

Any ideas on how to solve this?

PD: I imagine that this is related to #449

**Comment by vpolouchkine** [comment]
I don't believe it's possible to set the language of the simulator (see https://github.com/fastlane/snapshot/issues/365#issuecomment-172638332).

**Comment by freynolds** [comment]
Yes, @vpolouchkine after some more reading I read that.
I was just going to update that with this type of localization
`NSLocalizedString("Alert Success", tableName: "sdk", comment: "Alert Success")`
I'm having errors. It's using the english table instead of the spanish one.

**Comment by jeffreyjackson** [comment]
What file are you using for your localized string? @freynolds

**Comment by freynolds** [comment]
Base App: Generic.strings
SDK: SDK.strings
I use submodules to add the sdk to several apps and the sdk has some layouts that have localized strings.

**Comment by i2amsam** [comment]
@freynolds was this working before and then regressed with the 1.9.0 update?

**Comment by freynolds** [comment]
@i2amsam I can't be sure, I though so, but now I don't really know...

How can I translate the whole app, all the strings? any idea?

**Comment by skywinder** [comment]
Seems it's duplicate or related with #440

**Comment by jbonsant** [comment]
Same issue here since 1.9.0

**Comment by i2amsam** [comment]
@jbonsant was this working before and then regressed?  What `Xcode` version are you using?  What does your Snapfile have for languages and simulators?

**Comment by jbonsant** [comment]
Now i'm on 1.10. I implemented it on 1.9 and i'm not sure if it was working or not. 

Xcode 7.1.2

devices([
   "iPhone 6s",
   "iPhone 6s Plus",
   "iPhone 6",
   "iPhone 6 Plus",
   "iPhone 5",
   "iPhone 4s",
   "iPad Retina",
   "iPad Pro"
])

languages([
  "fr-FR"
])

**Comment by i2amsam** [comment]
@jbonsant could you clarify the behavior you are seeing (or not seeing) there are a few different issues in these tickets and I want to make sure they are not getting crossed.

**Comment by jbonsant** [comment]
All the simulators are starting in English although the screenshots are saved in fr-CA folder

**Comment by i2amsam** [comment]
Hmm, this is odd, @jbonsant could you try with `1.8.0`?

```
gem install snapshot -v 1.8.0
gem uninstall snapshot -v 1.10.0
snapshot
```

**Comment by jbonsant** [comment]
I fix my issue.

I was setting up launch arguments in my test file. It was overwriting the ones of Snapshot.

**Comment by i2amsam** [comment]
Ok, @freynolds could you post the full output from one of your runs?

**Comment by skywinder** [comment]
@jbonsant which test file?

**Comment by jbonsant** [comment]
My swift file with the XCTestCase taking the screenshots
