### ISSUE TITLE
Issue with launch_arguments

### ISSUE THREAD

**Issue by tache** [fastlane/snapshot#480]
Using `snapshot 1.11.0` I am either having a user issue with configuration, it does not work the way I think it should, or it is broke.

I have the following in my Snapfile:
```
launch_arguments([ "-adsDisabled YES" ])
```

In my Swift `XCTestCase` I have  
```
...
    let app = XCUIApplication()
    
    override func setUp() {
        super.setUp()
        setupSnapshot(app)
        app.launch()
    }
...
```

In my view controller of the app target, I have 
```
let FASTLANE_SNAPSHOT = NSUserDefaults.standardUserDefaults().boolForKey("FASTLANE_SNAPSHOT")
let ADS_DISABLED = NSUserDefaults.standardUserDefaults().boolForKey("adsDisabled")
```

when running `snapshot --verbose`, I do not see either as being set. 

When I add the following in the view controller, and then check out the `~/Library/Logs/snapshot/<app>.log`, I do not see either of the key/pairs set.  
```
print(NSUserDefaults.standardUserDefaults().dictionaryRepresentation());
```

**Comment by DJLectr0** [comment]
I have the exact same issue. Fresh install of snapshot.

**Comment by DJLectr0** [comment]
I have found the problem. When generating a new UI Test Target Xcode creates the following line in setUp(): `XCUIApplication().launch()`. If you remove this it works!

**Comment by tache** [comment]
I commented out the `app.launch()` from Setup as shown in the above example, and I still do not see the settings.

**Comment by vpolouchkine** [comment]
Can you please post your full Snapfile and XCTestCase class? Thanks!
