### ISSUE TITLE
Alternative Snapfiles

### ISSUE THREAD

**Issue by martnst** [fastlane/snapshot#481]
Hi *, 
I use `snapshot` not just for App Store screenshots but also for generating screenshots for my marketing website. For the website want more than 5 screenshots but only on one device and only in english. To control my UITests that take the screenshots I pass it a `launch_arguments` configured in the `Snapfile` along side with `devices` and `languages`.  

So wich this setup everything is great except I need to swap the Snapfiles (actually I am just adjusting a symlink) to choose which screenshots should be taken. Therefor I am wondering about specifying a Snapfile as a command line argument.

**Comment by vpolouchkine** [comment]
I don't believe you can specify multiple Snapfiles. Perhaps you can use multiple lanes and call snapshot with different sets of args?
